[project]
name = "mcp-source-relation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.2.1",
    "toml>=0.10.2",
]
